import { readFileSync } from 'node:fs'
import { describe, expect, test } from 'vitest'

const read = (path: string) => readFileSync(new URL(path, import.meta.url), 'utf8')

describe('prompt block overlay workspace contract', () => {
    test('adds a dedicated full-width tab without renumbering existing destinations', () => {
        const settings = read('../PromptPresetSettings.svelte')

        expect(settings).toContain("{ label: language.promptOverlay.tab, value: 5 }")
        expect(settings).toContain('{ label: language.parameters, value: 3 }')
        expect(settings).toContain('{ label: language.advancedSettings, value: 4 }')
        expect(settings).toContain('<PromptBlockOverlayWorkspace />')
        expect(settings).toContain('$PromptPresetSubmenuIndex === 5')
    })

    test('exposes source selection, per-block placement, targets, and a composed map', () => {
        const workspace = read('./PromptBlockOverlayWorkspace.svelte')
        const korean = read('../../../../lang/ko.ts')
        const english = read('../../../../lang/en.ts')

        expect(workspace).toContain('data-prompt-overlay-workspace')
        expect(workspace).toContain('DBState.db.promptBlockOverlay')
        expect(workspace).toContain('DBState.db.promptBlockOverlayProfiles')
        expect(workspace).toContain('createPromptBlockOverlayProfileFromPreset')
        expect(workspace).toContain("let extractionText = $state('📙')")
        expect(workspace).toContain('bind:value={extractionText}')
        expect(workspace).toContain('promptBlockMatchesExtractionText')
        expect(workspace).toContain('createPromptBlockOverlayProfileFromPreset(extractPreset, uuidv4(), extractionText)')
        expect(workspace).toContain('appendPromptBlockOverlayProfileFromPreset')
        expect(workspace).toContain('appendToProfile')
        expect(workspace).toContain('profileId')
        expect(workspace).toContain("{ value: 'before', label: language.promptOverlay.before }")
        expect(workspace).toContain("{ value: 'replace', label: language.promptOverlay.replace }")
        expect(workspace).toContain("{ value: 'after', label: language.promptOverlay.after }")
        expect(workspace).toContain('includeReferencedToggles')
        expect(workspace).toContain('language.promptOverlay.resultMap')
        expect(workspace).toContain('selectPromptBlockOverlayProfile')
        expect(workspace).toContain('updatePromptBlockOverlayConfig')
        expect(workspace).toContain('resolvePromptBlockOverlayReference')
        expect(workspace).toContain('missing-target')
        expect(workspace).toContain('aria-expanded')
        expect(workspace).toContain('use:resizeHandle')
        expect(workspace).toContain('use:tooltip')
        expect(workspace).not.toContain('language.promptOverlay.enabledHelp')
        expect(workspace).not.toContain('onCheckedChange={(enabled) => patchConfig({ enabled })}')
        expect(workspace).toContain('DBState.db.promptBlockOverlayApplicationPresets')
        expect(workspace).toContain('createPromptBlockOverlayApplicationPreset')
        expect(workspace).toContain('applyPromptBlockOverlayApplicationPreset')
        expect(workspace).toContain('overwritePromptBlockOverlayApplicationPreset')
        expect(workspace).toContain('saveApplicationPreset')
        expect(workspace).toContain('deleteApplicationPreset')
        expect(workspace).toContain('saveComposedAsNewPreset')
        expect(workspace).toContain('overwriteOriginalPreset')
        expect(workspace).toContain('alertInput(language.promptOverlay.newPresetNamePrompt')
        expect(workspace).toContain('composePromptBlockOverlay')
        expect(workspace).toContain('getEffectivePromptToggleTemplate')
        expect(workspace).toContain('saveCurrentPreset')
        expect(workspace).toContain('editResultBlock')
        expect(workspace).toContain('updatePromptBlockItemText')
        expect(workspace).toContain('class="result-content result-editor"')
        expect(workspace).toContain('class="top-tools"')
        expect(workspace).toContain('data-overlay-top-pane="extract"')
        expect(workspace).toContain('data-overlay-top-pane="presets"')
        expect(workspace).toContain('class="top-split-handle"')
        expect(workspace).toContain('startTopSplitResize')
        expect(workspace).toContain('--overlay-extract-width')
        expect(workspace).toContain('container-type: inline-size')
        expect(workspace).toContain('@container top-tools')
        expect(workspace).toContain('@container top-tools (max-width: 64rem)')
        expect(workspace).toContain('.preset-actions { grid-column: 1 / -1;')
        expect(workspace).toContain('let setupExpanded = $state(true)')
        expect(workspace).toContain('class="setup-toggle"')
        expect(workspace).toContain('aria-expanded={setupExpanded}')
        expect(workspace).toContain('{#if setupExpanded}')
        expect(workspace).toContain('renameProfile')
        expect(workspace).toContain('deleteProfile')
        expect(workspace).toContain('editBlockText')
        expect(workspace).toContain('duplicateBlock')
        expect(workspace).toContain('deleteBlock')
        expect(workspace).toContain('moveBlock')
        expect(workspace).toContain('let selectedSourceIndex = $state(-1)')
        expect(workspace).toContain('class="block-toolbar"')
        expect(workspace).toContain('class="block-selector"')
        expect(workspace).toContain('class:selected-block={selectedSourceIndex === index}')
        expect(workspace).toContain('class="selection-indicator"')
        expect(workspace).toContain('<CheckIcon size={14} />')
        expect(workspace).toContain('.mapping-row.selected-block::before')
        expect(workspace).toContain('.mapping-row:focus-within')
        expect(workspace).toContain('.block-selector:active')
        expect(workspace).toContain('class="mapping-control"')
        expect(workspace).toContain('class="mapping-control mapping-control--target"')
        expect(workspace).toContain('grid-template-columns: max-content minmax(0, 1fr);')
        expect(workspace).toContain('@media (prefers-reduced-motion: reduce)')
        expect(workspace).toContain('moveBlock(selectedSourceIndex, -5)')
        expect(workspace).toContain('moveBlock(selectedSourceIndex, 5)')
        expect(workspace).not.toContain('class="block-actions"')
        expect(workspace).toContain('language.promptOverlay.editBlockContent')
        expect(workspace).toContain('<textarea')
        expect(workspace).toContain('flex: 0 0 auto')
        expect(workspace).toContain('overflow-y: scroll')
        expect(korean).toContain('tab: "프롬프트 블록 인젝터"')
        expect(korean).toContain('extractTools: "블록 추출 도구"')
        expect(korean).toContain('applicationPreset: "블록 주입 프리셋"')
        expect(korean).toContain('profile: "추출된 블록"')
        expect(korean).toContain('sourceBlocks: "블록 주입 매핑"')
        expect(korean).toContain('saveComposedAsNew: "새로 저장"')
        expect(korean).toContain('overwriteOriginal: "원본 덮어쓰기"')
        expect(korean).toContain('resultMap: "블록 주입 프리뷰 + 에디터"')
        expect(english).toContain('tab: "Prompt block injector"')
    })
})
